export type UnitKind = "length" | "weight" | "temperature" | "volume" | "area" | "illuminance" | "torque" | "energy" | "speed" | "pressure" | "power" | "data_size" | "data_rate" | "time" | "currency" | "frequency" | "density" | "force" | "voltage" | "resistance" | "angle" | "luminous_intensity" | "fuel_economy";

export interface UnitDefinition {
  id: string;
  label: string;
  symbol: string;
  kind: UnitKind;
  toBase: (value: number) => number;
  fromBase: (value: number) => number;
  decimalPlaces?: number;
}

export interface ConversionContext {
  from: UnitDefinition;
  to: UnitDefinition;
  kind: UnitKind;
}

const units: Record<string, UnitDefinition> = {
  meter: {
    id: "meter",
    label: "Meter",
    symbol: "m",
    kind: "length",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  kilometer: {
    id: "kilometer",
    label: "Kilometer",
    symbol: "km",
    kind: "length",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 4
  },
  foot: {
    id: "foot",
    label: "Foot",
    symbol: "ft",
    kind: "length",
    toBase: (value) => value * 0.3048,
    fromBase: (value) => value / 0.3048,
    decimalPlaces: 4
  },
  inch: {
    id: "inch",
    label: "Inch",
    symbol: "in",
    kind: "length",
    toBase: (value) => value * 0.0254,
    fromBase: (value) => value / 0.0254,
    decimalPlaces: 4
  },
  centimeter: {
    id: "centimeter",
    label: "Centimeter",
    symbol: "cm",
    kind: "length",
    toBase: (value) => value / 100,
    fromBase: (value) => value * 100,
    decimalPlaces: 4
  },
  millimeter: {
    id: "millimeter",
    label: "Millimeter",
    symbol: "mm",
    kind: "length",
    toBase: (value) => value / 1000,
    fromBase: (value) => value * 1000,
    decimalPlaces: 4
  },
  yard: {
    id: "yard",
    label: "Yard",
    symbol: "yd",
    kind: "length",
    toBase: (value) => value * 0.9144,
    fromBase: (value) => value / 0.9144,
    decimalPlaces: 4
  },
  mile: {
    id: "mile",
    label: "Mile",
    symbol: "mi",
    kind: "length",
    toBase: (value) => value * 1609.344,
    fromBase: (value) => value / 1609.344,
    decimalPlaces: 4
  },
  nautical_mile: {
    id: "nautical_mile",
    label: "Nautical Mile",
    symbol: "nmi",
    kind: "length",
    toBase: (value) => value * 1852,
    fromBase: (value) => value / 1852,
    decimalPlaces: 4
  },
  gram: {
    id: "gram",
    label: "Gram",
    symbol: "g",
    kind: "weight",
    toBase: (value) => value / 1000,
    fromBase: (value) => value * 1000,
    decimalPlaces: 4
  },
  kilogram: {
    id: "kilogram",
    label: "Kilogram",
    symbol: "kg",
    kind: "weight",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  pound: {
    id: "pound",
    label: "Pound",
    symbol: "lb",
    kind: "weight",
    toBase: (value) => value * 0.45359237,
    fromBase: (value) => value / 0.45359237,
    decimalPlaces: 4
  },
  ounce: {
    id: "ounce",
    label: "Ounce",
    symbol: "oz",
    kind: "weight",
    toBase: (value) => value * 0.0283495231,
    fromBase: (value) => value / 0.0283495231,
    decimalPlaces: 4
  },
  stone: {
    id: "stone",
    label: "Stone",
    symbol: "st",
    kind: "weight",
    toBase: (value) => value * 6.35029318,
    fromBase: (value) => value / 6.35029318,
    decimalPlaces: 4
  },
  liter: {
    id: "liter",
    label: "Liter",
    symbol: "L",
    kind: "volume",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  milliliter: {
    id: "milliliter",
    label: "Milliliter",
    symbol: "mL",
    kind: "volume",
    toBase: (value) => value / 1000,
    fromBase: (value) => value * 1000,
    decimalPlaces: 4
  },
  gallon: {
    id: "gallon",
    label: "US Gallon",
    symbol: "gal",
    kind: "volume",
    toBase: (value) => value * 3.785411784,
    fromBase: (value) => value / 3.785411784,
    decimalPlaces: 4
  },
  gallon_uk: {
    id: "gallon_uk",
    label: "UK Gallon (Imperial)",
    symbol: "gal_uk",
    kind: "volume",
    toBase: (value) => value * 4.54609,
    fromBase: (value) => value / 4.54609,
    decimalPlaces: 4
  },
  quart: {
    id: "quart",
    label: "US Quart",
    symbol: "qt",
    kind: "volume",
    toBase: (value) => value * 0.946352946,
    fromBase: (value) => value / 0.946352946,
    decimalPlaces: 4
  },
  cup: {
    id: "cup",
    label: "US Cup",
    symbol: "cup",
    kind: "volume",
    // 1 US liquid gallon is 16 cups. 1 gallon is 3.785411784 liters.
    toBase: (value) => value * (3.785411784 / 16),
    fromBase: (value) => value / (3.785411784 / 16),
    decimalPlaces: 4
  },
  teaspoon: {
    id: "teaspoon",
    label: "Teaspoon",
    symbol: "tsp",
    kind: "volume",
    // 1 teaspoon = 5 mL = 0.005 liters (FDA/NIST standard for kitchen measures)
    toBase: (value) => value * 0.005,
    fromBase: (value) => value / 0.005,
    decimalPlaces: 4
  },
  celsius: {
    id: "celsius",
    label: "Celsius",
    symbol: "°C",
    kind: "temperature",
    toBase: (value) => value + 273.15,
    fromBase: (value) => value - 273.15,
    decimalPlaces: 2
  },
  fahrenheit: {
    id: "fahrenheit",
    label: "Fahrenheit",
    symbol: "°F",
    kind: "temperature",
    toBase: (value) => ((value - 32) * 5) / 9 + 273.15,
    fromBase: (value) => ((value - 273.15) * 9) / 5 + 32,
    decimalPlaces: 2
  },
  kelvin: {
    id: "kelvin",
    label: "Kelvin",
    symbol: "K",
    kind: "temperature",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  rankine: {
    id: "rankine",
    label: "Rankine",
    symbol: "°R",
    kind: "temperature",
    toBase: (value) => value / 1.8,
    fromBase: (value) => value * 1.8,
    decimalPlaces: 2
  },
  reaumur: {
    id: "reaumur",
    label: "Reaumur",
    symbol: "°Ré",
    kind: "temperature",
    toBase: (value) => value * 1.25 + 273.15,
    fromBase: (value) => (value - 273.15) / 1.25,
    decimalPlaces: 2
  },
  square_meter: {
    id: "square_meter",
    label: "Square Meter",
    symbol: "m²",
    kind: "area",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  square_foot: {
    id: "square_foot",
    label: "Square Foot",
    symbol: "ft²",
    kind: "area",
    toBase: (value) => value * 0.09290304,
    fromBase: (value) => value / 0.09290304,
    decimalPlaces: 4
  },
  acre: {
    id: "acre",
    label: "Acre",
    symbol: "ac",
    kind: "area",
    toBase: (value) => value * 4046.8564224,
    fromBase: (value) => value / 4046.8564224,
    decimalPlaces: 4
  },
  hectare: {
    id: "hectare",
    label: "Hectare",
    symbol: "ha",
    kind: "area",
    toBase: (value) => value * 10000,
    fromBase: (value) => value / 10000,
    decimalPlaces: 4
  },
  lumen: {
    id: "lumen",
    label: "Lumen",
    symbol: "lm",
    kind: "illuminance",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  lux: {
    id: "lux",
    label: "Lux",
    symbol: "lx",
    kind: "illuminance",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  newton_meter: {
    id: "newton_meter",
    label: "Newton-meter",
    symbol: "N·m",
    kind: "torque",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  foot_pound: {
    id: "foot_pound",
    label: "Foot-pound",
    symbol: "ft·lbf",
    kind: "torque",
    toBase: (value) => value * 1.355818,
    fromBase: (value) => value / 1.355818,
    decimalPlaces: 4
  },
  kilocalorie: {
    id: "kilocalorie",
    label: "Kilocalorie",
    symbol: "kcal",
    kind: "energy",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  kilojoule: {
    id: "kilojoule",
    label: "Kilojoule",
    symbol: "kJ",
    kind: "energy",
    toBase: (value) => value * 4.184,
    fromBase: (value) => value / 4.184,
    decimalPlaces: 2
  },
  joule: {
    id: "joule",
    label: "Joule",
    symbol: "J",
    kind: "energy",
    toBase: (value) => value / 4.184,
    fromBase: (value) => value * 4.184,
    decimalPlaces: 2
  },
  calorie: {
    id: "calorie",
    label: "Calorie",
    symbol: "cal",
    kind: "energy",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  btu: {
    id: "btu",
    label: "BTU",
    symbol: "BTU",
    kind: "energy",
    toBase: (value) => value / 0.252,
    fromBase: (value) => value * 0.252,
    decimalPlaces: 2
  },
  second: {
    id: "second",
    label: "Second",
    symbol: "s",
    kind: "time",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  minute: {
    id: "minute",
    label: "Minute",
    symbol: "min",
    kind: "time",
    toBase: (value) => value * 60,
    fromBase: (value) => value / 60,
    decimalPlaces: 2
  },
  hour: {
    id: "hour",
    label: "Hour",
    symbol: "h",
    kind: "time",
    toBase: (value) => value * 3600,
    fromBase: (value) => value / 3600,
    decimalPlaces: 4
  },
  day: {
    id: "day",
    label: "Day",
    symbol: "d",
    kind: "time",
    toBase: (value) => value * 86400,
    fromBase: (value) => value / 86400,
    decimalPlaces: 4
  },
  week: {
    id: "week",
    label: "Week",
    symbol: "wk",
    kind: "time",
    toBase: (value) => value * 604800,
    fromBase: (value) => value / 604800,
    decimalPlaces: 4
  },
  usd: {
    id: "usd",
    label: "US Dollar",
    symbol: "$",
    kind: "currency",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  eur: {
    id: "eur",
    label: "Euro",
    symbol: "€",
    kind: "currency",
    toBase: (value) => value * 1.10,
    fromBase: (value) => value / 1.10,
    decimalPlaces: 2
  },
  gbp: {
    id: "gbp",
    label: "British Pound",
    symbol: "£",
    kind: "currency",
    toBase: (value) => value * 1.27,
    fromBase: (value) => value / 1.27,
    decimalPlaces: 2
  },
  aud: {
    id: "aud",
    label: "Australian Dollar",
    symbol: "A$",
    kind: "currency",
    toBase: (value) => value * 0.65,
    fromBase: (value) => value / 0.65,
    decimalPlaces: 2
  },
  cad: {
    id: "cad",
    label: "Canadian Dollar",
    symbol: "C$",
    kind: "currency",
    toBase: (value) => value * 0.74,
    fromBase: (value) => value / 0.74,
    decimalPlaces: 2
  },
  jpy: {
    id: "jpy",
    label: "Japanese Yen",
    symbol: "¥",
    kind: "currency",
    toBase: (value) => value * 0.0067,
    fromBase: (value) => value / 0.0067,
    decimalPlaces: 2
  },
  btc: {
    id: "btc",
    label: "Bitcoin",
    symbol: "BTC",
    kind: "currency",
    toBase: (value) => value * 42500,
    fromBase: (value) => value / 42500,
    decimalPlaces: 8
  },
  hertz: {
    id: "hertz",
    label: "Hertz",
    symbol: "Hz",
    kind: "frequency",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  kilohertz: {
    id: "kilohertz",
    label: "Kilohertz",
    symbol: "kHz",
    kind: "frequency",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 2
  },
  megahertz: {
    id: "megahertz",
    label: "Megahertz",
    symbol: "MHz",
    kind: "frequency",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 2
  },
  gigahertz: {
    id: "gigahertz",
    label: "Gigahertz",
    symbol: "GHz",
    kind: "frequency",
    toBase: (value) => value * 1000000000,
    fromBase: (value) => value / 1000000000,
    decimalPlaces: 2
  },
  kilogram_per_cubic_meter: {
    id: "kilogram_per_cubic_meter",
    label: "Kilogram per Cubic Meter",
    symbol: "kg/m³",
    kind: "density",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  gram_per_cubic_centimeter: {
    id: "gram_per_cubic_centimeter",
    label: "Gram per Cubic Centimeter",
    symbol: "g/cm³",
    kind: "density",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 4
  },
  pounds_per_cubic_foot: {
    id: "pounds_per_cubic_foot",
    label: "Pounds per Cubic Foot",
    symbol: "lb/ft³",
    kind: "density",
    toBase: (value) => value * 16.01846,
    fromBase: (value) => value / 16.01846,
    decimalPlaces: 4
  },
  newton: {
    id: "newton",
    label: "Newton",
    symbol: "N",
    kind: "force",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 3
  },
  kilonewton: {
    id: "kilonewton",
    label: "Kilonewton",
    symbol: "kN",
    kind: "force",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 3
  },
  pound_force: {
    id: "pound_force",
    label: "Pound-Force",
    symbol: "lbf",
    kind: "force",
    toBase: (value) => value * 4.44822,
    fromBase: (value) => value / 4.44822,
    decimalPlaces: 3
  },
  volt: {
    id: "volt",
    label: "Volt",
    symbol: "V",
    kind: "voltage",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  millivolt: {
    id: "millivolt",
    label: "Millivolt",
    symbol: "mV",
    kind: "voltage",
    toBase: (value) => value / 1000,
    fromBase: (value) => value * 1000,
    decimalPlaces: 4
  },
  kilovolt: {
    id: "kilovolt",
    label: "Kilovolt",
    symbol: "kV",
    kind: "voltage",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 4
  },
  ohm: {
    id: "ohm",
    label: "Ohm",
    symbol: "Ω",
    kind: "resistance",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  kilohm: {
    id: "kilohm",
    label: "Kilohm",
    symbol: "kΩ",
    kind: "resistance",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 2
  },
  megohm: {
    id: "megohm",
    label: "Megohm",
    symbol: "MΩ",
    kind: "resistance",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 2
  },
  degree: {
    id: "degree",
    label: "Degree",
    symbol: "°",
    kind: "angle",
    toBase: (value) => value * 0.0174533,
    fromBase: (value) => value / 0.0174533,
    decimalPlaces: 4
  },
  radian: {
    id: "radian",
    label: "Radian",
    symbol: "rad",
    kind: "angle",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  cubic_centimeter: {
    id: "cubic_centimeter",
    label: "Cubic Centimeter",
    symbol: "cm³",
    kind: "volume",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  milligram: {
    id: "milligram",
    label: "Milligram",
    symbol: "mg",
    kind: "weight",
    toBase: (value) => value / 1000,
    fromBase: (value) => value * 1000,
    decimalPlaces: 3
  },
  meter_per_second: {
    id: "meter_per_second",
    label: "Meter per Second",
    symbol: "m/s",
    kind: "speed",
    toBase: (value) => value * 3.6,
    fromBase: (value) => value / 3.6,
    decimalPlaces: 2
  },
  candela: {
    id: "candela",
    label: "Candela",
    symbol: "cd",
    kind: "luminous_intensity",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  kilometers_per_hour: {
    id: "kilometers_per_hour",
    label: "Kilometers per Hour",
    symbol: "km/h",
    kind: "speed",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  miles_per_hour: {
    id: "miles_per_hour",
    label: "Miles per Hour",
    symbol: "mph",
    kind: "speed",
    toBase: (value) => value * 1.609344,
    fromBase: (value) => value / 1.609344,
    decimalPlaces: 2
  },
  atmosphere: {
    id: "atmosphere",
    label: "Atmosphere",
    symbol: "atm",
    kind: "pressure",
    toBase: (value) => value * 101325,
    fromBase: (value) => value / 101325,
    decimalPlaces: 4
  },
  pascal: {
    id: "pascal",
    label: "Pascal",
    symbol: "Pa",
    kind: "pressure",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  bar: {
    id: "bar",
    label: "Bar",
    symbol: "bar",
    kind: "pressure",
    toBase: (value) => value * 100000,
    fromBase: (value) => value / 100000,
    decimalPlaces: 4
  },
  psi: {
    id: "psi",
    label: "PSI (Pounds per Square Inch)",
    symbol: "psi",
    kind: "pressure",
    toBase: (value) => value * 6894.757293,
    fromBase: (value) => value / 6894.757293,
    decimalPlaces: 2
  },
  kilopascal: {
    id: "kilopascal",
    label: "Kilopascal",
    symbol: "kPa",
    kind: "pressure",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 2
  },
  watt: {
    id: "watt",
    label: "Watt",
    symbol: "W",
    kind: "power",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  kilowatt: {
    id: "kilowatt",
    label: "Kilowatt",
    symbol: "kW",
    kind: "power",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 3
  },
  megawatt: {
    id: "megawatt",
    label: "Megawatt",
    symbol: "MW",
    kind: "power",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 3
  },
  horsepower: {
    id: "horsepower",
    label: "Horsepower",
    symbol: "hp",
    kind: "power",
    toBase: (value) => value * 745.7,
    fromBase: (value) => value / 745.7,
    decimalPlaces: 3
  },
  bit: {
    id: "bit",
    label: "Bit",
    symbol: "b",
    kind: "data_size",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 0
  },
  byte: {
    id: "byte",
    label: "Byte",
    symbol: "B",
    kind: "data_size",
    toBase: (value) => value * 8,
    fromBase: (value) => value / 8,
    decimalPlaces: 2
  },
  kilobyte: {
    id: "kilobyte",
    label: "Kilobyte",
    symbol: "KB",
    kind: "data_size",
    toBase: (value) => value * 8000,
    fromBase: (value) => value / 8000,
    decimalPlaces: 2
  },
  megabyte: {
    id: "megabyte",
    label: "Megabyte",
    symbol: "MB",
    kind: "data_size",
    toBase: (value) => value * 8000000,
    fromBase: (value) => value / 8000000,
    decimalPlaces: 2
  },
  gigabyte: {
    id: "gigabyte",
    label: "Gigabyte",
    symbol: "GB",
    kind: "data_size",
    toBase: (value) => value * 1000000000,
    fromBase: (value) => value / 1000000000,
    decimalPlaces: 2
  },
  bit_per_second: {
    id: "bit_per_second",
    label: "Bit per Second",
    symbol: "bps",
    kind: "data_rate",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 0
  },
  kilobit_per_second: {
    id: "kilobit_per_second",
    label: "Kilobit per Second",
    symbol: "kbps",
    kind: "data_rate",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 2
  },
  megabit_per_second: {
    id: "megabit_per_second",
    label: "Megabit per Second",
    symbol: "Mbps",
    kind: "data_rate",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 2
  },
  megabyte_per_second: {
    id: "megabyte_per_second",
    label: "Megabyte per Second",
    symbol: "MB/s",
    kind: "data_rate",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 2
  },
  gigabit_per_second: {
    id: "gigabit_per_second",
    label: "Gigabit per Second",
    symbol: "Gbps",
    kind: "data_rate",
    toBase: (value) => value * 1000000000,
    fromBase: (value) => value / 1000000000,
    decimalPlaces: 2
  },
  terabit_per_second: {
    id: "terabit_per_second",
    label: "Terabit per Second",
    symbol: "Tbps",
    kind: "data_rate",
    toBase: (value) => value * 1000000000000,
    fromBase: (value) => value / 1000000000000,
    decimalPlaces: 2
  },
  terabyte: {
    id: "terabyte",
    label: "Terabyte",
    symbol: "TB",
    kind: "data_size",
    toBase: (value) => value * 8000000000,
    fromBase: (value) => value / 8000000000,
    decimalPlaces: 2
  },
  us_gallon: {
    id: "us_gallon",
    label: "US Gallon",
    symbol: "gal",
    kind: "volume",
    toBase: (value) => value * 3.78541,
    fromBase: (value) => value / 3.78541,
    decimalPlaces: 4
  },
  uk_gallon: {
    id: "uk_gallon",
    label: "UK Gallon",
    symbol: "UK gal",
    kind: "volume",
    toBase: (value) => value * 4.54609,
    fromBase: (value) => value / 4.54609,
    decimalPlaces: 4
  },
  attobyte: {
    id: "attobyte",
    label: "Attobyte",
    symbol: "aB",
    kind: "data_size",
    toBase: (value) => value / 1000000000000000000,
    fromBase: (value) => value * 1000000000000000000,
    decimalPlaces: 0
  },
  btu_per_hour: {
    id: "btu_per_hour",
    label: "BTU per Hour",
    symbol: "BTU/h",
    kind: "power",
    toBase: (value) => value * 0.293071,
    fromBase: (value) => value / 0.293071,
    decimalPlaces: 2
  },
  chf: {
    id: "chf",
    label: "Swiss Franc",
    symbol: "CHF",
    kind: "currency",
    toBase: (value) => value * 1.12,
    fromBase: (value) => value / 1.12,
    decimalPlaces: 2
  },
  eth: {
    id: "eth",
    label: "Ethereum",
    symbol: "ETH",
    kind: "currency",
    toBase: (value) => value * 2300,
    fromBase: (value) => value / 2300,
    decimalPlaces: 8
  },
  gradian: {
    id: "gradian",
    label: "Gradian",
    symbol: "grad",
    kind: "angle",
    toBase: (value) => value * Math.PI / 200,
    fromBase: (value) => value * 200 / Math.PI,
    decimalPlaces: 4
  },
  mil: {
    id: "mil",
    label: "Mil",
    symbol: "mil",
    kind: "angle",
    toBase: (value) => value * Math.PI / 3200,
    fromBase: (value) => value * 3200 / Math.PI,
    decimalPlaces: 4
  },
  turn: {
    id: "turn",
    label: "Turn",
    symbol: "turn",
    kind: "angle",
    toBase: (value) => value * 2 * Math.PI,
    fromBase: (value) => value / (2 * Math.PI),
    decimalPlaces: 4
  },
  arcminute: {
    id: "arcminute",
    label: "Arcminute",
    symbol: "arcmin",
    kind: "angle",
    toBase: (value) => value * Math.PI / 10800,
    fromBase: (value) => value * 10800 / Math.PI,
    decimalPlaces: 4
  },
  megajoule: {
    id: "megajoule",
    label: "Megajoule",
    symbol: "MJ",
    kind: "energy",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 2
  },
  rpm: {
    id: "rpm",
    label: "Revolution per Minute",
    symbol: "rpm",
    kind: "frequency",
    toBase: (value) => value / 60,
    fromBase: (value) => value * 60,
    decimalPlaces: 2
  },
  inr: {
    id: "inr",
    label: "Indian Rupee",
    symbol: "₹",
    kind: "currency",
    toBase: (value) => value * 0.012,
    fromBase: (value) => value / 0.012,
    decimalPlaces: 2
  },
  arcsecond: {
    id: "arcsecond",
    label: "Arcsecond",
    symbol: "arcsec",
    kind: "angle",
    toBase: (value) => value * Math.PI / 648000,
    fromBase: (value) => value * 648000 / Math.PI,
    decimalPlaces: 6
  },
  megawatt_hour: {
    id: "megawatt_hour",
    label: "Megawatt Hour",
    symbol: "MWh",
    kind: "energy",
    toBase: (value) => value * 3600000000,
    fromBase: (value) => value / 3600000000,
    decimalPlaces: 2
  },
  petabyte: {
    id: "petabyte",
    label: "Petabyte",
    symbol: "PB",
    kind: "data_size",
    toBase: (value) => value * 8000000000000000,
    fromBase: (value) => value / 8000000000000000,
    decimalPlaces: 2
  },
  terahertz: {
    id: "terahertz",
    label: "Terahertz",
    symbol: "THz",
    kind: "frequency",
    toBase: (value) => value * 1000000000000,
    fromBase: (value) => value / 1000000000000,
    decimalPlaces: 2
  },
  long_ton: {
    id: "long_ton",
    label: "Long Ton",
    symbol: "ton (long)",
    kind: "weight",
    toBase: (value) => value * 1016.04691,
    fromBase: (value) => value / 1016.04691,
    decimalPlaces: 4
  },
  microgram: {
    id: "microgram",
    label: "Microgram",
    symbol: "mcg",
    kind: "weight",
    toBase: (value) => value / 1000000000,
    fromBase: (value) => value * 1000000000,
    decimalPlaces: 6
  },
  gigabyte_per_second: {
    id: "gigabyte_per_second",
    label: "Gigabyte per Second",
    symbol: "GB/s",
    kind: "data_rate",
    toBase: (value) => value * 8000000000,
    fromBase: (value) => value / 8000000000,
    decimalPlaces: 2
  },
  kibibyte: {
    id: "kibibyte",
    label: "Kibibyte",
    symbol: "KiB",
    kind: "data_size",
    toBase: (value) => value * 8192,
    fromBase: (value) => value / 8192,
    decimalPlaces: 2
  },
  mebibyte: {
    id: "mebibyte",
    label: "Mebibyte",
    symbol: "MiB",
    kind: "data_size",
    toBase: (value) => value * 8388608,
    fromBase: (value) => value / 8388608,
    decimalPlaces: 2
  },
  radian_per_second: {
    id: "radian_per_second",
    label: "Radian per Second",
    symbol: "rad/s",
    kind: "frequency",
    toBase: (value) => value * 1000000000,
    fromBase: (value) => value / 1000000000,
    decimalPlaces: 4
  },
  short_ton: {
    id: "short_ton",
    label: "Short Ton",
    symbol: "ton (short)",
    kind: "weight",
    toBase: (value) => value * 907.18474,
    fromBase: (value) => value / 907.18474,
    decimalPlaces: 4
  },
  tonne: {
    id: "tonne",
    label: "Tonne",
    symbol: "t",
    kind: "weight",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 4
  },
  kpa: {
    id: "kpa",
    label: "Kilopascal",
    symbol: "kPa",
    kind: "pressure",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 2
  },
  cubic_foot: {
    id: "cubic_foot",
    label: "Cubic Foot",
    symbol: "ft³",
    kind: "volume",
    toBase: (value) => value * 28.3168,
    fromBase: (value) => value / 28.3168,
    decimalPlaces: 4
  },
  cubic_inch: {
    id: "cubic_inch",
    label: "Cubic Inch",
    symbol: "in³",
    kind: "volume",
    toBase: (value) => value * 0.0163871,
    fromBase: (value) => value / 0.0163871,
    decimalPlaces: 6
  },
  cubic_meter: {
    id: "cubic_meter",
    label: "Cubic Meter",
    symbol: "m³",
    kind: "volume",
    toBase: (value) => value * 1000,
    fromBase: (value) => value / 1000,
    decimalPlaces: 4
  },
  cubic_yard: {
    id: "cubic_yard",
    label: "Cubic Yard",
    symbol: "yd³",
    kind: "volume",
    toBase: (value) => value * 764.555,
    fromBase: (value) => value / 764.555,
    decimalPlaces: 4
  },
  knot: {
    id: "knot",
    label: "Knot",
    symbol: "kn",
    kind: "speed",
    toBase: (value) => value * 0.51444,
    fromBase: (value) => value / 0.51444,
    decimalPlaces: 4
  },
  mach: {
    id: "mach",
    label: "Mach",
    symbol: "M",
    kind: "speed",
    toBase: (value) => value * 343,
    fromBase: (value) => value / 343,
    decimalPlaces: 4
  },
  mile_per_hour: {
    id: "mile_per_hour",
    label: "Mile per Hour",
    symbol: "mph",
    kind: "speed",
    toBase: (value) => value * 0.44704,
    fromBase: (value) => value / 0.44704,
    decimalPlaces: 4
  },
  mile_per_second: {
    id: "mile_per_second",
    label: "Mile per Second",
    symbol: "mi/s",
    kind: "speed",
    toBase: (value) => value * 1609.34,
    fromBase: (value) => value / 1609.34,
    decimalPlaces: 4
  },
  micrometer: {
    id: "micrometer",
    label: "Micrometer",
    symbol: "µm",
    kind: "length",
    toBase: (value) => value / 1000000,
    fromBase: (value) => value * 1000000,
    decimalPlaces: 6
  },
  gallon_per_100_miles: {
    id: "gallon_per_100_miles",
    label: "Gallon per 100 Miles",
    symbol: "gal/100mi",
    kind: "fuel_economy",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  liter_per_100_kilometers: {
    id: "liter_per_100_kilometers",
    label: "Liter per 100 Kilometers",
    symbol: "L/100km",
    kind: "fuel_economy",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  liter_per_mile: {
    id: "liter_per_mile",
    label: "Liter per Mile",
    symbol: "L/mi",
    kind: "fuel_economy",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 4
  },
  mile_per_gallon_uk: {
    id: "mile_per_gallon_uk",
    label: "Mile per UK Gallon",
    symbol: "mpg (UK)",
    kind: "fuel_economy",
    toBase: (value) => value * 0.425144,
    fromBase: (value) => value / 0.425144,
    decimalPlaces: 2
  },
  millisecond: {
    id: "millisecond",
    label: "Millisecond",
    symbol: "ms",
    kind: "time",
    toBase: (value) => value / 1000,
    fromBase: (value) => value * 1000,
    decimalPlaces: 6
  },
  inch_of_mercury: {
    id: "inch_of_mercury",
    label: "Inch of Mercury",
    symbol: "inHg",
    kind: "pressure",
    toBase: (value) => value * 3386.39,
    fromBase: (value) => value / 3386.39,
    decimalPlaces: 4
  },
  megapascal: {
    id: "megapascal",
    label: "Megapascal",
    symbol: "MPa",
    kind: "pressure",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 2
  },
  millibar: {
    id: "millibar",
    label: "Millibar",
    symbol: "mbar",
    kind: "pressure",
    toBase: (value) => value * 100,
    fromBase: (value) => value / 100,
    decimalPlaces: 2
  },
  newton_per_square_meter: {
    id: "newton_per_square_meter",
    label: "Newton per Square Meter",
    symbol: "N/m²",
    kind: "pressure",
    toBase: (value) => value,
    fromBase: (value) => value,
    decimalPlaces: 2
  },
  torr: {
    id: "torr",
    label: "Torr",
    symbol: "Torr",
    kind: "pressure",
    toBase: (value) => value * 133.322,
    fromBase: (value) => value / 133.322,
    decimalPlaces: 4
  },
  decade: {
    id: "decade",
    label: "Decade",
    symbol: "decade",
    kind: "time",
    toBase: (value) => value * 315360000,
    fromBase: (value) => value / 315360000,
    decimalPlaces: 6
  },
  month: {
    id: "month",
    label: "Month",
    symbol: "month",
    kind: "time",
    toBase: (value) => value * 2592000,
    fromBase: (value) => value / 2592000,
    decimalPlaces: 4
  },
  year: {
    id: "year",
    label: "Year",
    symbol: "yr",
    kind: "time",
    toBase: (value) => value * 31536000,
    fromBase: (value) => value / 31536000,
    decimalPlaces: 6
  },
  square_centimeter: {
    id: "square_centimeter",
    label: "Square Centimeter",
    symbol: "cm²",
    kind: "area",
    toBase: (value) => value / 10000,
    fromBase: (value) => value * 10000,
    decimalPlaces: 6
  },
  square_inch: {
    id: "square_inch",
    label: "Square Inch",
    symbol: "in²",
    kind: "area",
    toBase: (value) => value * 0.00064516,
    fromBase: (value) => value / 0.00064516,
    decimalPlaces: 6
  },
  square_kilometer: {
    id: "square_kilometer",
    label: "Square Kilometer",
    symbol: "km²",
    kind: "area",
    toBase: (value) => value * 1000000,
    fromBase: (value) => value / 1000000,
    decimalPlaces: 4
  },
  square_mile: {
    id: "square_mile",
    label: "Square Mile",
    symbol: "mi²",
    kind: "area",
    toBase: (value) => value * 2589988,
    fromBase: (value) => value / 2589988,
    decimalPlaces: 4
  },
  square_yard: {
    id: "square_yard",
    label: "Square Yard",
    symbol: "yd²",
    kind: "area",
    toBase: (value) => value * 0.83612736,
    fromBase: (value) => value / 0.83612736,
    decimalPlaces: 4
  },
  tablespoon: {
    id: "tablespoon",
    label: "Tablespoon",
    symbol: "tbsp",
    kind: "volume",
    toBase: (value) => value * 14.787,
    fromBase: (value) => value / 14.787,
    decimalPlaces: 4
  },
  square_millimeter: {
    id: "square_millimeter",
    label: "Square Millimeter",
    symbol: "mm²",
    kind: "area",
    toBase: (value) => value / 1000000,
    fromBase: (value) => value * 1000000,
    decimalPlaces: 8
  },
  gigawatt: {
    id: "gigawatt",
    label: "Gigawatt",
    symbol: "GW",
    kind: "power",
    toBase: (value) => value * 1000000000,
    fromBase: (value) => value / 1000000000,
    decimalPlaces: 2
  },
  metric_horsepower: {
    id: "metric_horsepower",
    label: "Metric Horsepower",
    symbol: "PS",
    kind: "power",
    toBase: (value) => value * 735.5,
    fromBase: (value) => value / 735.5,
    decimalPlaces: 2
  }
};

const aliasToUnitId: Record<string, string> = {
  meter: "meter",
  meters: "meter",
  metre: "meter",
  metres: "meter",
  m: "meter",
  kilometre: "kilometer",
  kilometres: "kilometer",
  kilometer: "kilometer",
  kilometers: "kilometer",
  km: "kilometer",
  foot: "foot",
  feet: "foot",
  ft: "foot",
  inch: "inch",
  inches: "inch",
  in: "inch",
  centimeter: "centimeter",
  centimeters: "centimeter",
  centimetre: "centimeter",
  centimetres: "centimeter",
  cm: "centimeter",
  millimeter: "millimeter",
  millimeters: "millimeter",
  millimetre: "millimeter",
  millimetres: "millimeter",
  mm: "millimeter",
  yard: "yard",
  yards: "yard",
  yd: "yard",
  mile: "mile",
  miles: "mile",
  mi: "mile",
  nautical_mile: "nautical_mile",
  nautical_miles: "nautical_mile",
  nmi: "nautical_mile",
  "nautical mile": "nautical_mile",
  "nautical miles": "nautical_mile",
  nm: "nautical_mile",
  gram: "gram",
  grams: "gram",
  g: "gram",
  kilogram: "kilogram",
  kilograms: "kilogram",
  kilogramme: "kilogram",
  kilogrammes: "kilogram",
  kg: "kilogram",
  pound: "pound",
  pounds: "pound",
  lb: "pound",
  lbs: "pound",
  ounce: "ounce",
  ounces: "ounce",
  oz: "ounce",
  stone: "stone",
  stones: "stone",
  liter: "liter",
  liters: "liter",
  litre: "liter",
  litres: "liter",
  l: "liter",
  milliliter: "milliliter",
  milliliters: "milliliter",
  millilitre: "milliliter",
  millilitres: "milliliter",
  ml: "milliliter",
  gallon: "gallon",
  gallons: "gallon",
  gal: "gallon",
  gallon_uk: "gallon_uk",
  gallon_imp: "gallon_uk",
  imperial_gallon: "gallon_uk",
  "imperial gallon": "gallon_uk",
  "uk gallon": "gallon_uk",
  "UK gallon": "gallon_uk",
  quart: "quart",
  quarts: "quart",
  qt: "quart",
  cup: "cup",
  cups: "cup",
  teaspoon: "teaspoon",
  teaspoons: "teaspoon",
  tsp: "teaspoon",
  tsps: "teaspoon",
  "tea spoon": "teaspoon",
  "tea spoons": "teaspoon",
  celsius: "celsius",
  "degrees celsius": "celsius",
  celcius: "celsius",
  "degrees celcius": "celsius",
  fahrenheit: "fahrenheit",
  "degrees fahrenheit": "fahrenheit",
  kelvin: "kelvin",
  kelvins: "kelvin",
  rankine: "rankine",
  rankines: "rankine",
  "degrees rankine": "rankine",
  reaumur: "reaumur",
  reaumurs: "reaumur",
  "degrees reaumur": "reaumur",
  "°Ré": "reaumur",
  squaremeter: "square_meter",
  squaremeters: "square_meter",
  sqm: "square_meter",
  "square metre": "square_meter",
  "square meter": "square_meter",
  "square meters": "square_meter",
  "square metres": "square_meter",
  squarefoot: "square_foot",
  squarefeet: "square_foot",
  "square foot": "square_foot",
  "square feet": "square_foot",
  sqft: "square_foot",
  acre: "acre",
  acres: "acre",
  hectare: "hectare",
  hectares: "hectare",
  ha: "hectare",
  lumen: "lumen",
  lumens: "lumen",
  lm: "lumen",
  lux: "lux",
  luxes: "lux",
  lx: "lux",
  newton_meter: "newton_meter",
  "newton-meter": "newton_meter",
  "newton meter": "newton_meter",
  "n·m": "newton_meter",
  "nm": "newton_meter",
  foot_pound: "foot_pound",
  "foot-pound": "foot_pound",
  "foot pound": "foot_pound",
  "ft·lbf": "foot_pound",
  "ftlbf": "foot_pound",
  "ft-lbf": "foot_pound",
  "ft-lb": "foot_pound",
  "lb-ft": "foot_pound",
  kilocalorie: "kilocalorie",
  "kilocalories": "kilocalorie",
  "kcal": "kilocalorie",
  "kcals": "kilocalorie",
  "Calorie": "kilocalorie",
  "Calories": "kilocalorie",
  "food calorie": "kilocalorie",
  "food calories": "kilocalorie",
  "large calorie": "kilocalorie",
  kilojoule: "kilojoule",
  "kilojoules": "kilojoule",
  "kJ": "kilojoule",
  "kjs": "kilojoule",
  joule: "joule",
  "joules": "joule",
  "J": "joule",
  "js": "joule",
  calorie: "calorie",
  "calories": "calorie",
  "cal": "calorie",
  "cals": "calorie",
  "gram calorie": "calorie",
  "gram calories": "calorie",
  btu: "btu",
  "btus": "btu",
  "BTU": "btu",
  "BTUs": "btu",
  "british thermal unit": "btu",
  "british thermal units": "btu",
  "btu/h": "btu",
  "btuh": "btu",
  "small calorie": "calorie",
  "small calories": "calorie",
  second: "second",
  "seconds": "second",
  "s": "second",
  "sec": "second",
  "secs": "second",
  minute: "minute",
  "minutes": "minute",
  "min": "minute",
  "mins": "minute",
  "m": "minute",
  hour: "hour",
  "hours": "hour",
  "h": "hour",
  "hr": "hour",
  "hrs": "hour",
  day: "day",
  "days": "day",
  "d": "day",
  week: "week",
  "weeks": "week",
  "wk": "week",
  "wks": "week",
  usd: "usd",
  "US Dollar": "usd",
  "USD": "usd",
  "us dollar": "usd",
  "$": "usd",
  "dollar": "usd",
  "dollars": "usd",
  eur: "eur",
  "Euro": "eur",
  "EUR": "eur",
  "euro": "eur",
  "euros": "eur",
  "€": "eur",
  gbp: "gbp",
  "British Pound": "gbp",
  "GBP": "gbp",
  "british pound": "gbp",
  "pound": "gbp",
  "pounds": "gbp",
  "£": "gbp",
  aud: "aud",
  "Australian Dollar": "aud",
  "AUD": "aud",
  "australian dollar": "aud",
  cad: "cad",
  "Canadian Dollar": "cad",
  "CAD": "cad",
  "canadian dollar": "cad",
  jpy: "jpy",
  "Japanese Yen": "jpy",
  "JPY": "jpy",
  "japanese yen": "jpy",
  "¥": "jpy",
  btc: "btc",
  "Bitcoin": "btc",
  "BTC": "btc",
  "bitcoin": "btc",
  hertz: "hertz",
  "Hertz": "hertz",
  "Hz": "hertz",
  "hz": "hertz",
  kilohertz: "kilohertz",
  "Kilohertz": "kilohertz",
  "kHz": "kilohertz",
  "khz": "kilohertz",
  "kilohertz": "kilohertz",
  "kilo hertz": "kilohertz",
  megahertz: "megahertz",
  "Megahertz": "megahertz",
  "MHz": "megahertz",
  "mhz": "megahertz",
  "mega hertz": "megahertz",
  gigahertz: "gigahertz",
  "Gigahertz": "gigahertz",
  "GHz": "gigahertz",
  "ghz": "gigahertz",
  "giga hertz": "gigahertz",
  kilogram_per_cubic_meter: "kilogram_per_cubic_meter",
  "kg/m³": "kilogram_per_cubic_meter",
  "kg/m3": "kilogram_per_cubic_meter",
  "kilogram per cubic meter": "kilogram_per_cubic_meter",
  "kilograms per cubic meter": "kilogram_per_cubic_meter",
  gram_per_cubic_centimeter: "gram_per_cubic_centimeter",
  "g/cm³": "gram_per_cubic_centimeter",
  "g/cm3": "gram_per_cubic_centimeter",
  "gram per cubic centimeter": "gram_per_cubic_centimeter",
  "grams per cubic centimeter": "gram_per_cubic_centimeter",
  pounds_per_cubic_foot: "pounds_per_cubic_foot",
  "lb/ft³": "pounds_per_cubic_foot",
  "lb/ft3": "pounds_per_cubic_foot",
  "pound per cubic foot": "pounds_per_cubic_foot",
  "pounds per cubic foot": "pounds_per_cubic_foot",
  "lbs/ft³": "pounds_per_cubic_foot",
  "lbs/ft3": "pounds_per_cubic_foot",
  newton: "newton",
  "Newtons": "newton",
  "N": "newton",
  "newtons": "newton",
  kilonewton: "kilonewton",
  "Kilonewtons": "kilonewton",
  "kN": "kilonewton",
  "kilonewtons": "kilonewton",
  pound_force: "pound_force",
  "Pound-Force": "pound_force",
  "lbf": "pound_force",
  "pound-force": "pound_force",
  "pounds force": "pound_force",
  volt: "volt",
  "Volt": "volt",
  "V": "volt",
  "volts": "volt",
  millivolt: "millivolt",
  "Millivolt": "millivolt",
  "mV": "millivolt",
  "millivolts": "millivolt",
  "mv": "millivolt",
  kilovolt: "kilovolt",
  "Kilovolt": "kilovolt",
  "kV": "kilovolt",
  "kilovolts": "kilovolt",
  "kv": "kilovolt",
  ohm: "ohm",
  "Ohm": "ohm",
  "Ω": "ohm",
  "Ohms": "ohm",
  kilohm: "kilohm",
  "Kilohm": "kilohm",
  "kΩ": "kilohm",
  "kilohms": "kilohm",
  megohm: "megohm",
  "Megohm": "megohm",
  "MΩ": "megohm",
  "megohms": "megohm",
  degree: "degree",
  "Degree": "degree",
  "°": "degree",
  "degrees": "degree",
  "deg": "degree",
  radian: "radian",
  "Radian": "radian",
  "rad": "radian",
  "radians": "radian",
  liter: "liter",
  "Liter": "liter",
  "L": "liter",
  "liters": "liter",
  "litre": "liter",
  "litres": "liter",
  cubic_centimeter: "cubic_centimeter",
  "Cubic Centimeter": "cubic_centimeter",
  "cm³": "cubic_centimeter",
  "cm3": "cubic_centimeter",
  "cubic centimeter": "cubic_centimeter",
  "cubic centimeters": "cubic_centimeter",
  "cc": "cubic_centimeter",
  milligram: "milligram",
  "Milligram": "milligram",
  "mg": "milligram",
  "milligrams": "milligram",
  meter_per_second: "meter_per_second",
  "Meter per Second": "meter_per_second",
  "m/s": "meter_per_second",
  "meters per second": "meter_per_second",
  "ms": "meter_per_second",
  "m per second": "meter_per_second",
  candela: "candela",
  "Candela": "candela",
  "cd": "candela",
  "candelas": "candela",
  "candle": "candela",
  "candles": "candela",
  kilometers_per_hour: "kilometers_per_hour",
  "km/h": "kilometers_per_hour",
  "kmh": "kilometers_per_hour",
  "km per hour": "kilometers_per_hour",
  "kilometers per hour": "kilometers_per_hour",
  miles_per_hour: "miles_per_hour",
  "mph": "miles_per_hour",
  "mi/h": "miles_per_hour",
  "miles per hour": "miles_per_hour",
  atmosphere: "atmosphere",
  atmospheres: "atmosphere",
  atm: "atmosphere",
  "atm": "atmosphere",
  "atmosphere": "atmosphere",
  "atmospheres": "atmosphere",
  "standard atmosphere": "atmosphere",
  pascal: "pascal",
  pascals: "pascal",
  pa: "pascal",
  "Pa": "pascal",
  "pascal": "pascal",
  "pascals": "pascal",
  "pascal (pa)": "pascal",
  "pascals (pa)": "pascal",
  bar: "bar",
  bars: "bar",
  psi: "psi",
  psig: "psi",
  psia: "psi",
  "pounds per square inch": "psi",
  "pound per square inch": "psi",
  kilopascal: "kilopascal",
  kilopascals: "kilopascal",
  kpa: "kilopascal",
  "kPa": "kilopascal",
  kPas: "kilopascal",
  "kilopascals": "kilopascal",
  watt: "watt",
  watts: "watt",
  w: "watt",
  "W": "watt",
  "watts": "watt",
  kilowatt: "kilowatt",
  kilowatts: "kilowatt",
  kw: "kilowatt",
  "kW": "kilowatt",
  "kilowatts": "kilowatt",
  megawatt: "megawatt",
  megawatts: "megawatt",
  mw: "megawatt",
  "MW": "megawatt",
  "megawatts": "megawatt",
  horsepower: "horsepower",
  hp: "horsepower",
  "horse power": "horsepower",
  bit: "bit",
  bits: "bit",
  b: "bit",
  "b": "bit",
  byte: "byte",
  bytes: "byte",
  "B": "byte",
  "bytes": "byte",
  kilobyte: "kilobyte",
  kilobytes: "kilobyte",
  kb: "kilobyte",
  "KB": "kilobyte",
  megabyte: "megabyte",
  megabytes: "megabyte",
  mb: "megabyte",
  "MB": "megabyte",
  gigabyte: "gigabyte",
  gigabytes: "gigabyte",
  gb: "gigabyte",
  "GB": "gigabyte",
  "bit per second": "bit_per_second",
  bps: "bit_per_second",
  "bps": "bit_per_second",
  kilobit_per_second: "kilobit_per_second",
  "kilobit per second": "kilobit_per_second",
  kbps: "kilobit_per_second",
  "kbps": "kilobit_per_second",
  "megabit per second": "megabit_per_second",
  mbps: "megabit_per_second",
  "Mbps": "megabit_per_second",
  "MB/s": "megabyte_per_second",
  "mb/s": "megabyte_per_second",
  "megabyte per second": "megabyte_per_second",
  gigabit_per_second: "gigabit_per_second",
  "gigabit per second": "gigabit_per_second",
  gbps: "gigabit_per_second",
  "Gbps": "gigabit_per_second",
  terabit_per_second: "terabit_per_second",
  "terabit per second": "terabit_per_second",
  tbps: "terabit_per_second",
  "Tbps": "terabit_per_second",
  terabyte: "terabyte",
  terabytes: "terabyte",
  tb: "terabyte",
  "TB": "terabyte",
  us_gallon: "us_gallon",
  "us gallon": "us_gallon",
  "US gallon": "us_gallon",
  "us gallons": "us_gallon",
  "gallon (us)": "us_gallon",
  uk_gallon: "uk_gallon",
  "uk gallon": "uk_gallon",
  "UK gallon": "uk_gallon",
  "uk gallons": "uk_gallon",
  "gallon (uk)": "uk_gallon",
  "imperial gallon": "uk_gallon",
  attobyte: "attobyte",
  attobytes: "attobyte",
  "aB": "attobyte",
  btu_per_hour: "btu_per_hour",
  "btu per hour": "btu_per_hour",
  "BTU/h": "btu_per_hour",
  "BTU/hr": "btu_per_hour",
  chf: "chf",
  "Swiss Franc": "chf",
  "CHF": "chf",
  "swiss franc": "chf",
  eth: "eth",
  "Ethereum": "eth",
  "ETH": "eth",
  "ethereum": "eth",
  gradian: "gradian",
  gradians: "gradian",
  "grad": "gradian",
  "gon": "gradian",
  mil: "mil",
  mils: "mil",
  "angular mil": "mil",
  turn: "turn",
  turns: "turn",
  "full turn": "turn",
  "revolution": "turn",
  arcminute: "arcminute",
  arcminutes: "arcminute",
  "arc minute": "arcminute",
  arcmin: "arcminute",
  "arcmin": "arcminute",
  megajoule: "megajoule",
  megajoules: "megajoule",
  "mj": "megajoule",
  "MJ": "megajoule",
  rpm: "rpm",
  "revolutions per minute": "rpm",
  "revolution per minute": "rpm",
  inr: "inr",
  "Indian Rupee": "inr",
  "INR": "inr",
  "indian rupee": "inr",
  "₹": "inr",
  arcsecond: "arcsecond",
  arcseconds: "arcsecond",
  "arc second": "arcsecond",
  arcsec: "arcsecond",
  "arcsec": "arcsecond",
  megawatt_hour: "megawatt_hour",
  "megawatt hour": "megawatt_hour",
  "MWh": "megawatt_hour",
  mwh: "megawatt_hour",
  petabyte: "petabyte",
  petabytes: "petabyte",
  "pb": "petabyte",
  "PB": "petabyte",
  terahertz: "terahertz",
  terahertzs: "terahertz",
  "thz": "terahertz",
  "THz": "terahertz",
  long_ton: "long_ton",
  "long ton": "long_ton",
  "long_ton": "long_ton",
  "imperial ton": "long_ton",
  microgram: "microgram",
  micrograms: "microgram",
  "mcg": "microgram",
  "µg": "microgram",
  "ug": "microgram",
  gigabyte_per_second: "gigabyte_per_second",
  "gigabyte per second": "gigabyte_per_second",
  "GB/s": "gigabyte_per_second",
  "GBps": "gigabyte_per_second",
  kibibyte: "kibibyte",
  kibibytes: "kibibyte",
  "KiB": "kibibyte",
  "kib": "kibibyte",
  mebibyte: "mebibyte",
  mebibytes: "mebibyte",
  "MiB": "mebibyte",
  "mib": "mebibyte",
  radian_per_second: "radian_per_second",
  "radian per second": "radian_per_second",
  "rad/s": "radian_per_second",
  "radians per second": "radian_per_second",
  short_ton: "short_ton",
  "short ton": "short_ton",
  "short_ton": "short_ton",
  "us ton": "short_ton",
  tonne: "tonne",
  "metric ton": "tonne",
  "metric_ton": "tonne",
  "tonnes": "tonne",
  "t": "tonne",
  horsepower: "horsepower",
  "horse power": "horsepower",
  "hp": "horsepower",
  "HP": "horsepower",
  "mechanical horsepower": "horsepower",
  kpa: "kpa",
  kilopascal: "kpa",
  "kilopascals": "kpa",
  "kPa": "kpa",
  "KPa": "kpa",
  cubic_foot: "cubic_foot",
  "cubic foot": "cubic_foot",
  "cubic feet": "cubic_foot",
  "cu ft": "cubic_foot",
  "ft³": "cubic_foot",
  "ft^3": "cubic_foot",
  cubic_inch: "cubic_inch",
  "cubic inch": "cubic_inch",
  "cubic inches": "cubic_inch",
  "cu in": "cubic_inch",
  "in³": "cubic_inch",
  "in^3": "cubic_inch",
  cubic_meter: "cubic_meter",
  "cubic meter": "cubic_meter",
  "cubic metres": "cubic_meter",
  "m³": "cubic_meter",
  "m^3": "cubic_meter",
  cubic_yard: "cubic_yard",
  "cubic yard": "cubic_yard",
  "cubic yards": "cubic_yard",
  "yd³": "cubic_yard",
  "yd^3": "cubic_yard",
  knot: "knot",
  knots: "knot",
  "kn": "knot",
  "nautical mile per hour": "knot",
  mach: "mach",
  "m": "mach",
  mile_per_hour: "mile_per_hour",
  "mile per hour": "mile_per_hour",
  "miles per hour": "mile_per_hour",
  "mph": "mile_per_hour",
  "MPH": "mile_per_hour",
  mile_per_second: "mile_per_second",
  "mile per second": "mile_per_second",
  "miles per second": "mile_per_second",
  "mi/s": "mile_per_second",
  micrometer: "micrometer",
  micrometers: "micrometer",
  "µm": "micrometer",
  "um": "micrometer",
  "micron": "micrometer",
  gallon_per_100_miles: "gallon_per_100_miles",
  "gallon per 100 miles": "gallon_per_100_miles",
  "gal/100mi": "gallon_per_100_miles",
  liter_per_100_kilometers: "liter_per_100_kilometers",
  "liter per 100 kilometers": "liter_per_100_kilometers",
  "L/100km": "liter_per_100_kilometers",
  liter_per_mile: "liter_per_mile",
  "liter per mile": "liter_per_mile",
  "L/mi": "liter_per_mile",
  mile_per_gallon_uk: "mile_per_gallon_uk",
  "mile per uk gallon": "mile_per_gallon_uk",
  "mpg uk": "mile_per_gallon_uk",
  millisecond: "millisecond",
  milliseconds: "millisecond",
  "ms": "millisecond",
  "millis": "millisecond",
  inch_of_mercury: "inch_of_mercury",
  "inches of mercury": "inch_of_mercury",
  "inHg": "inch_of_mercury",
  megapascal: "megapascal",
  megapascals: "megapascal",
  "MPa": "megapascal",
  millibar: "millibar",
  millibars: "millibar",
  "mbar": "millibar",
  newton_per_square_meter: "newton_per_square_meter",
  "newton per square meter": "newton_per_square_meter",
  "N/m²": "newton_per_square_meter",
  "N/m2": "newton_per_square_meter",
  "n/m²": "newton_per_square_meter",
  torr: "torr",
  decade: "decade",
  decades: "decade",
  month: "month",
  months: "month",
  year: "year",
  years: "year",
  "yr": "year",
  square_centimeter: "square_centimeter",
  "square centimeter": "square_centimeter",
  "cm²": "square_centimeter",
  "cm2": "square_centimeter",
  square_inch: "square_inch",
  "square inch": "square_inch",
  "in²": "square_inch",
  "in2": "square_inch",
  square_kilometer: "square_kilometer",
  "square kilometer": "square_kilometer",
  "km²": "square_kilometer",
  "km2": "square_kilometer",
  square_mile: "square_mile",
  "square mile": "square_mile",
  "mi²": "square_mile",
  "mi2": "square_mile",
  square_yard: "square_yard",
  "square yard": "square_yard",
  "yd²": "square_yard",
  "yd2": "square_yard",
  tablespoon: "tablespoon",
  tablespoons: "tablespoon",
  "tbsp": "tablespoon",
  "table spoon": "tablespoon",
  square_millimeter: "square_millimeter",
  "square millimeter": "square_millimeter",
  "mm²": "square_millimeter",
  "mm2": "square_millimeter",
  gigawatt: "gigawatt",
  gigawatts: "gigawatt",
  "GW": "gigawatt",
  metric_horsepower: "metric_horsepower",
  "metric horsepower": "metric_horsepower",
  "PS": "metric_horsepower",
  "CV": "metric_horsepower",
  "ch": "metric_horsepower"
};

const slugSuffixes = ["-converter", "-calculator", "-conversion"];

export function getUnitById(id: string): UnitDefinition | undefined {
  return units[id];
}

export function resolveUnit(token: string): UnitDefinition | undefined {
  const normalized = normalizeToken(token);
  const direct = aliasToUnitId[normalized];
  if (direct) {
    return units[direct];
  }

  const collapsed = normalized.replace(/\s+/g, "");
  const collapsedMatch = aliasToUnitId[collapsed];
  if (collapsedMatch) {
    return units[collapsedMatch];
  }

  return undefined;
}

export function parseConversionFromSlug(slug: string): ConversionContext | null {
  const candidates = extractUnitTokens(slug);
  if (!candidates) {
    return null;
  }

  const fromUnit = resolveUnit(candidates.from);
  const toUnit = resolveUnit(candidates.to);

  if (!fromUnit || !toUnit) {
    return null;
  }

  if (fromUnit.kind !== toUnit.kind) {
    return null;
  }

  return {
    from: fromUnit,
    to: toUnit,
    kind: fromUnit.kind
  };
}

export function convertValue(
  value: number,
  direction: "forward" | "reverse",
  context: ConversionContext
) {
  if (Number.isNaN(value)) {
    return NaN;
  }

  if (direction === "forward") {
    const base = context.from.toBase(value);
    return context.to.fromBase(base);
  }

  const base = context.to.toBase(value);
  return context.from.fromBase(base);
}

export interface ConversionTableRow {
  input: number;
  output: number;
}

export function buildConversionTable(
  seeds: number[],
  context: ConversionContext,
  direction: "forward" | "reverse" = "forward"
): ConversionTableRow[] {
  return seeds.map((seed) => ({
    input: seed,
    output: convertValue(seed, direction, context)
  }));
}

function extractUnitTokens(slug: string): { from: string; to: string } | null {
  const sanitized = slugSuffixes.reduce(
    (value, suffix) => value.replace(new RegExp(`${suffix}$`), ""),
    slug
  );

  const match = sanitized.match(/(.+?)-to-(.+)/);
  if (!match) {
    return null;
  }

  return {
    from: match[1],
    to: match[2]
  };
}

function normalizeToken(token: string) {
  return token
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}
